/* eslint-disable prettier/prettier */
export const texts = {
  common: {
    administration: 'Administration',
    administrator: 'Administrator',
    apiKey: 'API Key',
    appName: 'Omni SaaS',
    builtIn: 'Built In',
    cancel: 'Cancel',
    common: 'Common',
    confirm: 'Confirm',
    copied: 'Text added to clipboard',
    createdAt: 'Created',
    currency: 'Currency',
    dangerZone: 'Danger Zone',
    dashboard: 'Dashboard',
    default: 'Default',
    description: 'Description',
    disabled: 'Disabled',
    documentation: 'Official Documentation',
    documentationLabel: 'Read more at the',
    dropZone: 'Drag and drop some file here, or click to select files.',
    dropZoneDrop: 'Drop files.',
    edit: 'Edit',
    email: 'Email',
    enabled: 'Enabled',
    endpoint: 'Endpoint',
    environment: 'Environment',
    error: 'Failed to make update.',
    failed: 'Failed',
    generate: 'Generate',
    headers: 'Headers',
    health: 'Health',
    healthy: 'Healthy',
    hideFileUpload: 'Hide Files Sidebar',
    installation: 'Installation',
    installing: 'Installing',
    loginButton: 'Login',
    loginFailed: 'Username or password not correct.',
    loginText: 'Login with username and password',
    logout: 'Logout',
    more: 'More',
    name: 'Name',
    no: 'No',
    notFound: 'Not found',
    page: (page: number, total: number) => `Page ${page} of ${total}`,
    password: 'Password',
    passwordConfirm: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    pending: 'Pending',
    perDay: 'day',
    perHour: 'hour',
    perMonth: 'month',
    remove: 'Remove',
    rename: 'Rename',
    required: 'Required field',
    roles: 'Roles',
    save: 'Save',
    saved: 'Saved successfully.',
    search: 'Search',
    settings: 'Settings',
    status: 'Status',
    subtitle: 'Subtitle',
    succeeded: 'Succeeded',
    text: 'Text',
    title: 'Title',
    totalPrice: 'Total',
    unhealthy: 'Unhealthy',
    uncheckedHealth: 'Health unchecked',
    url: 'Url',
    userGroup: 'User Group',
    userGroups: 'User Groups',
    yes: 'Yes',
  },
  billing: {
    amount: 'Amount',
    dueDate: 'Due Date',
    emptyLabel: 'No invoice yet',
    emptyText: 'Wait for the first billing period or create a new deployment.',
    headline: 'Billing',
    notPaid: 'Not Paid',
    number: 'Invoice',
    paid: 'Paid',
    paymentDue: 'Payment Due',
    pending: 'Pending',
    portal: 'Payment Portal',
    voided: 'Voided',
  },
  dashboard: {},
  deployments: {
    create: 'New Deployment',
    deployHeadline: 'Deploy new Service',
    deploymentHeadline: 'Deployment',
    deployingInfo: 'This instance is currently deployed. Your resources may still be finishing installing and booting up during the first few minutes of activation.',
    edit: 'Edit Deployment (Soon)',
    estimatedPrice: 'Estimated Price',
    estimatedPriceText: 'Price is monthly, based on a 30-day average, assuming no changes to parameters.',
    emptyLabel: 'No deployment yet',
    emptyText: 'Install a service to create your first deployment.',
    fixedPrice: 'Fixed Price',
    headline: 'Deployments',
    resourceCores: 'Cores',
    resourceMemory: 'Memory',
    resourceStorage: 'Storage',
    resourceVolumes: 'Volumes',
    selectService: 'Select the Service you want to deploy',
  },
  login: {
    loginButton: (provider: string) => `Login with ${provider}`,
    loginHint: 'Login to your account',
    welcome: 'Welcome to Omni SaaS 👋',
  },
  members: {
    headline: 'Members',
  },
  services: {
    create: 'New Service',
    createFailed: 'Failed to create Service',
    createVersion: 'New Version',
    createVersionFailed: 'Failed to create Service Version',
    definition: 'YAML Definition',
    definitionHint: 'The YAML Definition cannot be changed later. Versions are basically immutable',
    empty: 'No service found.',
    fixedPrice: 'Fixed base price',
    headline: 'Services',
    isActive: 'Is Active',
    isPublic: 'Is Public',
    latestVersion: 'Latest Version',
    numDeployments: 'Num deployments',
    pricing: 'Pricing',
    pricePerCpuHour: 'Price per CPU / hour',
    pricePerCpuHourLabel: 'CPU / hour',
    pricePerMemoryGbHour: 'Price per GB Memory / hour',
    pricePerMemoryGbHourLabel: 'GB Memory / hour',
    pricePerStorageGbMonth: 'Price per GB Storage / month',
    pricePerStorageGbMonthLabel: 'GB Memory / hour',
    pricePerVolumeGbHour: 'Price per GB Volume / hour',
    pricePerVolumeGbHourLabel: 'GB Volume / hour',
    update: 'Update Service',
    updateFailed: 'Failed to update Service',
    updateVersion: 'Update Service Version',
    updateVersionFailed: 'Failed to update Service Version',
  },
  userGroups: {
    create: 'Create User Group',
    createFailed: 'Failed to create User Group',
    empty: 'No user groups found.',
    removeConfirmText: 'Do you really want to remove the User Group?',
    removeConfirmTitle: 'Remove User Group',
    headline: 'Groups',
    update: 'Update User Group',
    updateFailed: 'Failed to update User Group',
  },
  users: {
    create: 'Create User',
    createFailed: 'Failed to ceate User',
    empty: 'No users found.',
    removeConfirmText: 'Do you really want to remove the User?',
    removeConfirmTitle: 'Remove User',
    headline: 'Users',
    update: 'Update User',
    updateFailed: 'Failed to update User',
  },
  teams: {
    createTitle: 'Create Team',
    createText: 'You are not part of any team yet. Create a new one to invite other members and manage resources.',
    selectTeam: 'Select Team',
  },
  theme: {
    appName: 'App Name',
    appNameHints: 'The name of this app, used for the title and the menu.',
    customCss: 'Custom CSS',
    footerLinks: 'Footer Links',
    footerText: 'Footer Text',
    headerColor: 'Header Color',
    headline: 'Theme',
    logo: 'Logo',
    logoCurrent: 'Current logo',
    logoHint: 'The logo is shown on the admin page and the login screen.',
    logoUpdateFailed: 'Failed to update logo.',
    primaryColor: 'Primary Color',
    primaryContentColor: 'Primary Content Color',
    settings: 'General Settings',
    updateFailed: 'Failed to update settings.',
    welcomeText: 'Welcome Text',
    welcomeTextHints: 'Only shown on the login page.',
  },
};
