export const texts = {
  common: {
    administration: 'Administration',
    administrator: 'Administrator',
    apiKey: 'API Key',
    appName: 'Company Chat',
    builtIn: 'Built In',
    cancel: 'Cancel',
    chatUser: 'Chat User',
    confirm: 'Confirm',
    copied: 'Text added to clipboard',
    dangerZone: 'Danger Zone',
    dashboard: 'Dashboard',
    default: 'Default',
    disabled: 'Disabled',
    documentation: 'Official Documentation',
    documentationLabel: 'Read more at the',
    dropZone: 'Drag and drop some file here, or click to select files.',
    dropZoneDrop: 'Drop files.',
    edit: 'Edit',
    email: 'Email',
    enabled: 'Enabled',
    endpoint: 'Endpoint',
    error: 'Failed to make update.',
    generate: 'Generate',
    headers: 'Headers',
    hideFileUpload: 'Hide Files Sidebar',
    loginButton: 'Login',
    loginFailed: 'Username or password not correct.',
    loginText: 'Login with username and password',
    logout: 'Logout',
    monthlyTokens: 'Monthly tokens',
    monthlyUserTokens: 'Monthly tokens / User',
    name: 'Name',
    no: 'No',
    page: (page: number, total: number) => `Page ${page} of ${total}`,
    password: 'Password',
    passwordConfirm: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    remove: 'Remove',
    rename: 'Rename',
    required: 'Required field',
    roles: 'Roles',
    save: 'Save',
    saved: 'Saved successfully.',
    search: 'Search',
    sidebarLeftHide: 'Hide conversations',
    sidebarLeftShow: 'Show conversations',
    sidebarRightHide: 'Hide files',
    sidebarRightShow: 'Show files',
    subtitle: 'Subtitle',
    text: 'Text',
    title: 'Title',
    tokens: 'Tokens',
    userGroup: 'User Group',
    userGroups: 'User Groups',
    yes: 'Yes',
  },
  chat: {
    newChat: 'New Chat',
    placeholder: 'Message AI...',
    rateConversation: 'Was this conversation helpful so far?',
    rating: {
      incorrect: 'Not factually correct',
      instructions_not_followed: "Didn't follow instructions",
      insufficient_style: "Don't like the style",
      lazy: 'Being lazy',
      refused: "Refused when it shouldn't have",
    },
    ratingHint: 'Tell us more',
    removeConversationConfirmText: 'Do you really want to remove the conversation?',
    removeConversationConfirmTitle: 'Remove conversation',
    removeConversationFailed: 'Failed to remove conversation',
    renameConversationFailed: 'Failed to rename conversaiton',
    sourceAI: 'Friendly AI',
    sourceHuman: 'You',
    thisMonth: 'Previous 30 Days',
    thisWeek: 'Previous 7 Days',
    today: 'Today',
    yesterday: 'Yesterday',
  },
  dashboard: {
    ratings: 'Ratings',
    tokensPerModelChart: 'Tokens per Model',
    tokensTotalChat: 'Total Tokens',
  },
  extensions: {
    add: 'Add Extension',
    all: 'All Extensions',
    configured: 'Configured Extensions',
    createDeployment: 'Create Deployment',
    createDeploymentFailed: 'Failed to create deployment.',
    createExtension: 'Create Extension',
    createExtensionFailed: 'Failed to create Extension',
    deploymentNotSelected: 'No deployment selected.',
    deployments: 'Deployments',
    deploymentsEmpty: 'No deployment created yet.',
    executorEndpoint: 'Executor Endpoint',
    executorEndpointHints:
      'The executor is a special service that handles the complete chat flow and only provides the answer. For special cases, where full control over the chat is needed.',
    executorHeaders: 'Executor Headers',
    headline: 'Extensions',
    removeDeploymentConfirmText: 'Do you really want to remove the deployment?',
    removeDeploymentConfirmTitle: 'Remove extension',
    removeDeploymentFailed: 'Failed to remove deployment',
    removeExtensionConfirmText: 'Do you really want to remove the extension?',
    removeExtensionConfirmTitle: 'Remove extension',
    removeExtensionFailed: 'Failed to remove deployment',
    test: 'Test',
    testFailed: 'Extension is not valid',
    testSuccess: 'Extension is valid.',
    testTooltip: 'Test the config with the current form values, saving not required.',
    typeModels: 'Models',
    typeOther: 'Other',
    typeTools: 'Tools',
    updateDeployment: 'Update Deployment',
    updateDeploymentFailed: 'Failed to update Deployment',
    updateExtension: 'Update Extension',
    updateExtensionFailed: 'Failed to update Extension',
    userGroupsHints: 'Restrict the access to the deployment to certain user groups.',
    warningNoModel: 'You have to configure or enable at least one model.',
    warningTooManyModels: 'You have more than one model enabled, the first model will be chosen by default for new chats.',
  },
  files: {
    bucketNotSelected: 'No bucket selected.',
    buckets: 'Buckets',
    bucketsEmpty: 'No bucket created yet.',
    createBucket: 'Create Bucket',
    createBucketFailed: 'Failed to create bucket.',
    headline: 'Files',
    isDefault: 'Is Default',
    removeBucketConfirmText: 'Do you really want to remove the bucket?',
    removeBucketConfirmTitle: 'Remove bucket',
    removeBucketFailed: 'Failed to remove bucket',
    removeFileConfirmText: 'Do you really want to remove the file?',
    removeFileConfirmTitle: 'Remove file',
    removeFileFailed: 'Failed to delete file.',
    testFailed: 'Bucket is not valid',
    testSuccess: 'Bucket is valid.',
    testTooltip: 'Test the config with the current form values, saving not required.',
    updateBucketFailed: 'Failed to update bucket.',
    uploadFailed: 'Failed to upload file.',
    uploading: 'Uploading File',
  },
  login: {
    loginButton: (provider: string) => `Login with ${provider}`,
    loginHint: 'Login to your account',
    welcome: 'Welcome to codecentric Company Chat 👋',
  },
  userGroups: {
    create: 'Create User Group',
    empty: 'No user groups found.',
    removeConfirmText: 'Do you really want to remove the User Group?',
    removeConfirmTitle: 'Remove User Group',
    headline: 'Groups',
    update: 'Update User Group',
    updateFailed: 'Failed to update User Group',
  },
  users: {
    create: 'Create User',
    empty: 'No users found.',
    removeConfirmText: 'Do you really want to remove the User?',
    removeConfirmTitle: 'Remove User',
    headline: 'Users',
    update: 'Update User',
    updateFailed: 'Failed to update User',
  },
  theme: {
    agentName: 'Agent Name',
    agentNameHints: 'How the agent is named in the chat.',
    appName: 'App Name',
    appNameHints: 'The name of this app, used for the title and the menu.',
    customCss: 'Custom CSS',
    footer: 'Chat Footer',
    footerHints: 'Text, that is rendered below the input in the main chat view. Show the text from the theme and deployment.',
    headline: 'Theme',
    logo: 'Logo',
    logoCurrent: 'Current logo',
    logoHint: 'The logo is shown on the admin page and the login screen.\n\nAt the moment it is not used for the chat.',
    logoUpdateFailed: 'Failed to update logo.',
    primaryColor: 'Primary Color',
    primaryContentColor: 'Primary Content Color',
    settings: 'General Settings',
    suggestions: 'Chat Suggestions',
    suggestionsHints: 'Shows suggestions for the chat. Shows all items from the theme and deployment.',
    updateFailed: 'Failed to update settings.',
    welcomeText: 'Welcome Text',
    welcomeTextHints: 'Only shown on the login page.',
  },
};
