{
  "parameters": [
    {
      "name": "domain",
      "label": "Public Domain",
      "type": "string",
      "required": true,
      "display": true
    },
    {
      "name": "region",
      "label": "Region",
      "type": "string",
      "required": true,
      "display": true,
      "allowedValues": [
        {
          "value": "fra",
          "label": "Frankfurt"
        },
        {
          "value": "ams",
          "label": "Amsterday"
        },
        {
          "value": "ewr",
          "label": "New Jersey"
        }
      ]
    },
    {
      "name": "plan",
      "label": "Plan",
      "type": "string",
      "required": true,
      "display": true,
      "allowedValues": [
        {
          "value": "cores_4",
          "label": "4 Cores, 8 GB RAM, 160 GB SSD"
        },
        {
          "value": "cores_8",
          "label": "8 Cores, 32 GB RAM, 640 GB SSD"
        },
        {
          "value": "cores_16",
          "label": "16 Cores, 64 GB RAM, 1280 GB SSD"
        }
      ]
    },
    {
      "name": "googleClient",
      "label": "Google Client ID",
      "type": "string",
      "required": false,
      "section": "Authentication"
    },
    {
      "name": "googleSecret",
      "label": "Google Client Secret",
      "type": "string",
      "required": false,
      "section": "Authentication"
    },
    {
      "name": "microsoftClient",
      "label": "Microsoft Client ID",
      "type": "string",
      "required": false,
      "section": "Authentication"
    },
    {
      "name": "microsoftSecret",
      "label": "Microsoft Client Secret",
      "type": "string",
      "required": false,
      "section": "Authentication"
    },
    {
      "name": "githubClient",
      "label": "Github Client ID",
      "type": "string",
      "required": false,
      "section": "Authentication"
    },
    {
      "name": "githubSecret",
      "label": "Github Client Secret",
      "type": "string",
      "required": false,
      "section": "Authentication"
    }
  ],
  "afterInstallationInstructions": "Create a new A record from your domain **${parameters.domain}** to the IP address of the virtual machine. Ensure that you do not enable https termination in Cloudflare.\r\n\r\nUse the following credentials to login to Squidex:\r\n\r\n* Username: **changeme@squidex.io**\r\n* Password: **changeme**\r\n\r\nChange them as soon as possible.",
  "pricingModel": "fixed",
  "resources": [
    {
      "name": "Virtual Machine",
      "id": "vm",
      "type": "vultr-vm",
      "parameters": {
        "apiKey": "${env.apiKey}",
        "app": "docker",
        "region": "${parameters.region}"
      },
      "mappings": {
        "plan": {
          "value": "${parameters.plan}",
          "map": {
            "cores_4": "vc2-4c-8gb",
            "cores_8": "vc2-8c-32gb",
            "cores_16": "vc2-16c-64gb"
          }
        }
      }
    },
    {
      "name": "Squidex",
      "id": "squidex",
      "type": "docker-compose-ssh",
      "parameters": {
        "dockerComposeUrl": "https://raw.githubusercontent.com/Squidex/squidex-hosting/refs/heads/master/docker-compose/docker-compose.yml",
        "host": "${context.vm.host}",
        "sshUser": "${context.vm.sshUser}",
        "sshPassword": "${context.vm.sshPassword}",
        "SQUIDEX_GITHUBCLIENT": "${parameters.githubClient}",
        "SQUIDEX_GITHUBSECRET": "${parameters.githubSecret}",
        "SQUIDEX_GOOGLECLIENT": "${parameters.googleClient}",
        "SQUIDEX_GOOGLESECRET": "${parameters.googleSecret}",
        "SQUIDEX_MICROSOFTCLIENT": "${parameters.microsoftClient}",
        "SQUIDEX_MICROSOFTSECRET": "${parameters.microsoftSecret}",
        "SQUIDEX_DOMAIN": "${parameters.domain}",
      },
      "healthChecks": [
        {
          "name": "Default",
          "url": "https://${parameters.domain}/healthz",
          "type": "http"
        }
      ]
    }
  ],
  "prices": [
    {
      "target": "${parameters.plan}",
      "test": "cores_4",
      "amount": 80
    },
    {
      "target": "${parameters.plan}",
      "test": "cores_8",
      "amount": 320
    },
    {
      "target": "${parameters.plan}",
      "test": "cores_16",
      "amount": 640
    }
  ],
  "usage": {
    "totalCores": "${parameters.mongoDbNodes * parameters.mongoDbCoresPerNode + (parameters.squidexNodes + 1) * parameters.squidexCoresPerNode}",
    "totalMemoryGB": "${parameters.mongoDbNodes * parameters.mongoDbMemoryPerNode + (parameters.squidexNodes + 1) * parameters.squidexDbMemoryPerNode}",
    "totalStorageGB": "${parameters.mongoDbNodes * parameters.mongoDbVolumePerNode}",
    "totalVolumeGB": "${parameters.squidexStorage}"
  }
}